### ISSUE TITLE
container-entrypoint handling of arguments with spaces

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/sti-base#79]
:question: Is this a bug or a feature?

The current implementation of the script:
```bash
cmd="$1"; shift
exec $cmd "$@"
#    ^^^^
```

It handles quoting everywhere except in one place.

It makes a difference when the first argument to the entrypoint has spaces. The current implementation:

- cannot run executables with a space in the name (perhaps not that bad)
- works when multiple arguments are passed as a single argument (to my surprise):

    ```console
$ ./container-entrypoint 'bundle exec rake test'
Could not locate Gemfile
```
- doesn't work in the same case above when the command should not be blindly split on spaces:

    ```console
$ /bin/sh -c "echo 123"
123
$ ./container-entrypoint '/bin/sh -c "echo 123"'
123": -c: line 0: unexpected EOF while looking for matching `"'
123": -c: line 1: syntax error: unexpected end of file
```

This affects image users relying on the entrypoint, for example when they use build hooks.

Shall we correct the quoting, or is it implementing the intended behavior?

**Comment by rhcarvalho** [comment]
@bparees @mfojtik @hhorak PTAL

**Comment by mfojtik** [comment]
> $ ./container-entrypoint 'bundle exec rake test'

@rhcarvalho is the Gemfile located in the same directory where that command runs?

**Comment by rhcarvalho** [comment]
@mfojtik perhaps that example deviated the attention from the problem. The problem is that it worked.

My expectation is that it should have failed just like:

```console
$ exec 'bundle exec rake test'
bash: exec: bundle exec rake test: not found
```

(I'm running that in a random directory, was not expecting any tests to be run)

**Comment by mfojtik** [comment]
@rhcarvalho I see what you mean now, we shift the args and since the $1 is the "quoted" command we effectively remove it. Then we "exec "$@"" :-) I wonder how that can work as well.

**Comment by bparees** [comment]
@rhcarvalho it's not clear to me what you're proposing we do instead?
`exec "$@"`

or `exec "$cmd" "$@"`
?

**Comment by hhorak** [comment]
> @rhcarvalho I see what you mean now, we shift the args and since the $1 is the "quoted" command we effectively remove it. Then we "exec "$@"" :-) I wonder how that can work as well.

As for the example with `./container-entrypoint 'bundle exec rake test'` -- what happens here is to store $1 into $cmd (=`bundle exec rake test`), which is then called without quotes, so what is being called is actually `exec bundle exec rake test`, that's why it works.

I'm still not sure whether this is what we need or not.. Is `./container-entrypoint '/bin/sh -c "echo 123"'` some real-life example?

**Comment by rhcarvalho** [comment]
@bparees instead of making a proposal upfront I wanted to understand if the current implementation was the desired behavior or just accidental.

@hhorak a real-life use case came up when I was testing build hooks.
By default, the container entrypoint is `container-entrypoint`, and then using the build hooks you can pass arguments to the default entrypoint as an array of strings (each element of the array is one argument).
Passing `["bundle exec rake test"]` worked, to my surprise. Your explanation of why it works is correct.

However, a build hook might contain other types of things where the lack of quotes would cause issues with the single string approach (that users could "get used to"). One example would be running a SQL query:

`["mysql -u root -p somedb -e 'select * from mytable'"]` :arrow_right: this would pass incorrect arguments to `mysql`, namely `(-u, root, -p, somedb, -e, 'select, *, from, mytable')`.

In both examples above, passing each argument as a separate string in the array would produce the correct result:
- `["bundle", "exec", "rake", "test"]`
- `["mysql", "-u", "root", "-p", "somedb", "-e", "'select * from mytable'"]`

A proposal to fix the quoting problem would be either

```bash
#!/bin/bash
set -eu
cmd="$1"; shift
exec "$cmd" "$@"
```

or even shorter

```bash
#!/bin/bash
exec "$@"
```

Both proposals would make `["mysql -u root -p somedb -e 'select * from mytable'"]` cause an error saying "exec: mysql -u root -p somedb -e 'select * from mytable': not found", instead of running `mysql` with the wrong arguments.

**Comment by bparees** [comment]
@rhcarvalho thanks, the issue is much clearer to me now.

I guess i'm thinking what we have now is the best approach because while it breaks in your mysql scenario, your proposed fix is also broken for that scenario (though admittedly with a better error message).

But what we have now is works for the intuitive case, such as what you initially tried (and were surprised to see work). 

Is there any case where what we have now breaks now when it would *not* break if we made this change?  (regardless of whether it breaks differently)

**Comment by rhcarvalho** [comment]
It was counter-intuitive to me, I expected it to fail.
It should have been a single argument if the entrypoint was ["bash", "-c"] or similar.

I've seen in the past months errors like that in a few occasions, the last one in a BZ by QE testing my build hooks card :smile: 

That's why I was pushing forward to have a "script" instead of command/args syntax.

So while people do make mistakes, I think we should promote the usage of the right syntax, the one that will work every else -- instead of building reliance on a bug-feature that will only work under certain conditions. (What I understood so far is that the lack of quotes was not intentional)

User's understanding how to use Docker's syntax should never write a single string as argument, because that would fail in all other places: pod command, deployment hook, etc.

> Is there any case where what we have now breaks now when it would not break if we made this change?

It just comes to mind the unlike case were the executable has spaces in its name or path.

**Comment by bparees** [comment]
> It was counter-intuitive to me, I expected it to fail.

fair enough, but no one is going to explicitly do something they expect to fail as their intuitive guess as to how to do something.

> (What I understood so far is that the lack of quotes was not intentional)

i'm not sure about that, I think someone may have been trying to make "bundle exec rake ruby" work, actually.

that said, this is what we do in the jenkins image (which I pulled from the dockerhub jenkins image):
https://github.com/openshift/jenkins/blob/master/1/contrib/s2i/run#L108

so that would be consistent w/ what you're proposing.

Given that, i guess i can get behind making the change.
